### ISSUE TITLE
Create a registration and login page 

### ISSUE THREAD

**Issue by eyobofficial** [eyobofficial/orit-analysis#1]
## Goal
1. Build a user registration page and form with the following fields:
* First Name
* Last Name
* E-mail
* Username
* Password

2. Build a user login page and form with following fields:
* email / username field
* password

## Task
- [x] Create an `account` application.
- [x] Create a `registration` & `login` page.
- [x] Add custom backend `authentication` to login users with either their username or email address.
