### ISSUE TITLE
Install and setup `pipenv` 

### ISSUE THREAD

**Issue by eyobofficial** [eyobofficial/orit-analysis#13]
## Description
Replace the `pip` and `virtualenv` with the lastest `pipenv` package.

## Task
- [x] Install and setup `pipenv`.
- [x] Replace the `requirements.txt` file with `Pipfile` & `Pipfile.lock`.
- [x] Replace the `psycopg2` package with the newer `psycopg2-binary` package.
