### ISSUE TITLE
Change default database to MySQL

### ISSUE THREAD

**Issue by eyobofficial** [eyobofficial/orit-analysis#15]
## Summary
Change the current default database engine from `Postgres` to `MySQL`. 

## Task
- [x] Remove the old `postgres` connector packages.
- [x] Install and setup the `mysqlclient` connector package.
- [x] Replace the `ENGINE` section of the global `DATABASE` settings.
- [x] Update the `.travis.yml` configuration file.
