### ISSUE TITLE
Create common shared models

### ISSUE THREAD

**Issue by eyobofficial** [eyobofficial/orit-analysis#24]
## Goal
Create common models that are going to be shared by other apps. This models should be created in the `shared` app.

## Task
- [x] Create common models
- [x] Add necessary migrations
- [x] Register models to `shared/admin.py`.

#### ConstructionCategory
Field |  Field Type | Required | Description
-------- | ---------------- | -------------|----------------
title  | CharField    |  TRUE     |
icon    | CharField     | TRUE     |
order | IntegerField  | TRUE |
description | TextField | FALSE |

**Note**: This model tracks the major construction categories such. Examples: `Earthwork`, `Concrete Works`, `Block Works`, `Steel Works`,  `Finishing Works`, `Electrical Installations`, `Sanitary Installations`, `Site Works` etc.

#### Activity
Field |  Field Type | Required | Description
-------- | ---------------- | -------------|----------------
name  | CharField    |  TRUE     |

**Note**: This model will be used to track minor/sub-category works. Example: `site clearing`, `backfill`, `formwork`, `gypsum works` etc

#### Consultant / Contractor / Client
Field | Field Type | Required | Description
-------|----------------|--------------|----------------
short_name | CharField | TRUE |
long_name    | CharField | TRUE  |
logo   | ImageField | FALSE |
address | TextField | FALSE |
