### ISSUE TITLE
Rename the `ConstructionCategory` model to `Work`

### ISSUE THREAD

**Issue by eyobofficial** [eyobofficial/orit-analysis#28]
## Goal
Rename the name of the `ConstructionCategory` model to `Work`.

## Tasks
- [x] Rename model name
- [x] Generate migration files
- [x] Update the `shared/admin.py`
- [x] Rename `construction_categories.json` fixture to `works.json`.
