### ISSUE TITLE
Create and setup a new app called `boq`

### ISSUE THREAD

**Issue by eyobofficial** [eyobofficial/orit-analysis#30]
## Goal
Create and setup a new app called `boq` for managing `Bill of Quantity`. 

## Tasks
- [x] Create and install a new app called `boq`.
- [x] Add a URL route to the new app.
- [x] Add a blank overview page with a placeholder price analysis panel.
