### ISSUE TITLE
Remove the `boq` app and replace it with a new app called `price_analysis`

### ISSUE THREAD

**Issue by eyobofficial** [eyobofficial/orit-analysis#33]
## Goal
Bill of quantities is going to be a common feature for more future apps (Example: `payments`, `price_escalations`). Thus, it is better to remove the generic `boq` app and replace it with a more specific app called `price_analysis`.

The `price_analysis` app will be used for creating cost breakdowns for new construction items, bill of quantities and summary of bill of quantities.

## Tasks
- [x] Create a new app called `price_escalations`
- [x] Move all the templates, views and static assets of the `boq` app to the `price_analysis` app.
- [x] Remove the `boq` app.
