### ISSUE TITLE
Set up email service

### ISSUE THREAD

**Issue by eyobofficial** [eyobofficial/orit-analysis#5]
## Tasks

- [ ] Install `django-post_office` package to handle email
- [ ] Create a base email utility class which all other apps' email classes can inherit from
- [ ] Create a base email template
